#!/bin/bash

echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # # # INCIANDO INSTALAÇÃO # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "

echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # #  INCIANDO UPDATE  # # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "
sudo apt update -y
echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # #  INCIANDO UPGRADE # # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "
sudo apt upgrade -y
echo -e "# # # # # # # # # # # # # # # # # # # "
echo -e "# # #  INSTALANDO  NODE.js  # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # "
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates && curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt -y install nodejs
echo -e "# # # # # # # # # # # # # # # # # # # "
echo -e "# # #  CLONANDO REPOSITORIO # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # "
git clone https://github.com/parabaiano/botzap.git
echo -e "# # # # # # # # # # # # # # # # # # # # # # # "
echo -e "# # #  ABRINDO PASTA DO REPOSITORIO # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # # # # # "
cd botzap
echo -e "# # # # # # # # # # # # # # # # # # # # # # # "
echo -e "# # # INSTALANDO AS LIB DO REPOSITORIO # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # # # # # "
sudo npm install
echo -e "# # # # # # # # # # # # # # # # # # # "
echo -e "# # # RODANDO O BOT PARA TESTE # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # "
node bot.js
