#!/bin/bash

echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # # # INCIANDO INSTALAÇÃO # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "
clear
echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # #  INCIANDO UPDATE  # # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "
sudo apt update -y
echo -e "# # # # # # # # # # # # # # # # # # "
echo -e "# # #  INCIANDO UPGRADE # # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # "
sudo apt upgrade -y
echo -e "# # # # # # # # # # # # # # # # # # # "
echo -e "# # #  INSTALANDO  NODE.js  # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # "
sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates && curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt-get install nodejs
npm install -g npm@9.1.2
sudo apt-get install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev libasound2 -y
echo -e "# # # # # # # # # # # # # # # # # # # "
echo -e "# # #  CLONANDO REPOSITORIO # # # # # "
echo -e "# # # # # # # # # # # # # # # # # # # "
git clone https://github.com/parabaiano/botzap.git
sudo npm install -g pm2
sudo apt install nginx -y
sudo rm /etc/nginx/sites-enabled/default
sudo nano /etc/nginx/sites-available/botzap1 #nome do bot

#a baixo trocar só o server name pelo seu dominio
server {

  server_name bot.lcconect.host; 

  location / {

    proxy_pass http://127.0.0.1:8000;

    proxy_http_version 1.1;

    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Connection 'upgrade';

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_cache_bypass $http_upgrade;

  }

  }


sudo ln -s /etc/nginx/sites-available/botzap1 /etc/nginx/sites-enabled 
sudo nginx -t
sudo service nginx restart
sudo nano /etc/nginx/nginx.conf
####################################
# COPIA E COLA TUDO Q ESTA ABAIXO
####################################
client_max_body_size 20M;
# HANDLE BIGGER UPLOADS

####################################

sudo nginx -t
sudo service nginx restart
sudo apt-get install snapd
sudo snap install notes
sudo snap install --classic certbot
sudo certbot --nginx


pm2 list #para mostras todos os processos rodando 
